[general]
import = ["./themes/gnome_terminal.toml"]

# [env]
# # TERM = "xterm-256color"
# # TERM = "alacritty"
# TERM = "xterm-24bit"

[font]
# size = 10.5
size = 9

[font.normal]
family = "Hack"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "NumpadEnter"
mods = "None"

[mouse]
hide_when_typing = false
[[mouse.bindings]]
action = "PasteSelection"
mods = "Shift"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mods = "Shift"
mouse = "Right"

[scrolling]
history = 10000

[terminal]
# shell = "zj"
shell = "tmx"
